### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by PunchCakee** [libui-ng/libui-ng#212]
There hasn't been any commits in a while, whats the status of thr project?

**Comment by cody271** [comment]
Hi @PunchCakee, libui-ng is currently **mid-alpha** software. Please share with us your specific issue or feature request? Thanks

**Comment by szanni** [comment]
To add to that:
You can check out the controler gallery, tester and qa applications for an overview of what controls/widgets exist and are working on all supported platforms.
Development otherwise tends to be limited to the time contributors and maintainers have and often happens in surges.

Hope this helps.

**Comment by kojix2** [comment]
I believe commits are happening frequently enough for this project, but as the creator of a bindings, I would like to have a release.
