### ISSUE TITLE
Proposal: Haiku support

### ISSUE THREAD

**Issue by coolcoder613eb** [libui-ng/libui-ng#270]
Historically, libui included a backend for Haiku. However, this support was deprecated and removed at some point in 2016(?). I propose to resurrect the Haiku backend within libui. This entails ensuring compatibility with the latest versions of libui, and implementing new widgets where needed.

**Comment by matyalatte** [comment]
Unfortunately, it's hard to support it, I think.
The owner is busy and we don't have enough people even for the supported backends.
You can see some disscussion here https://github.com/libui-ng/libui-ng/issues/259

**Comment by rubyFeedback** [comment]
I'd love to work with HaikuOS. I gave up on it a while ago though as there is still no support
for ruby and I know way too little to help add support for it. As I myself got older, these days
I focus on operating systems I can use and worth with, which is Linux and also Windows and
libui-ng works on both. But of course if it were possible I'd be totally in support of that - like
making libui-ng super-mega-cross-platformy.

**Comment by rubyFeedback** [comment]
> The owner is busy and we don't have enough people even for the supported backends.

libui-ng could be forked again. :D But I agree with you - there need to be people with
domain specific knowledge out there. It's surprisingly hard to find people with enough
windows knowledge, for instance. Not sure where they all are. My own knowledge is
very limited overall - I know a bit about ruby and Linux, but I lack the knowledge one
needs for C/C++ and low-level stuff (or semi-low level ... like people who worked on 
windows writing applications and that).

**Comment by cody271** [comment]
> Historically, libui included a backend for Haiku.

This is no longer necessary, as Haiku is now sufficiently Unix-like to be supported by the Unix backend:

https://depot.haiku-os.org/gtk3

https://depot.haiku-os.org/meson

**Comment by matyalatte** [comment]
> This is no longer necessary, as Haiku is now sufficiently Unix-like to be supported by the Unix backend:

Tested on the latest release. (R1/beta4)
![haiku](https://github.com/libui-ng/libui-ng/assets/69258547/a35bb3d0-3725-4082-967f-97da80c5c2f6)

```shell
pkgman install meson ninja gtk3_devel
git clone https://github.com/libui-ng/libui-ng.git
cd libui-ng
meson setup build
meson compile -C build
./build/meson-out/controlgallery
```

Users need to install gtk themselves, but it works fine.

**Comment by coolcoder613eb** [comment]
I have already tried that, and I know the GTK backend runs, but unfortunately, GTK does *not* look or feel remotely native on Haiku, and looks as out of place as a Motif application would on GNOME.
QT, on the other hand looks better, not being implemented using xlibe(a X11 compatibility layer).
As for ruby support on Haiku, @rubyFeedback, ruby seems to be ported.
One of my other projects is [Haiku-PyAPI](https://github.com/coolcoder613eb/Haiku-PyAPI), Python bindings for the Haiku API, so I am somewhat familiar, although not so much with the C++ side of things.

**Comment by szanni** [comment]
As much as I am fascinated by the Haiku project, it is _very_ niche.
Unless somebody steps up and does the legwork or there is some Haiku funding pool to tap into that I'm unaware of, I sadly don't see this happening. We're missing QT as well for the KDE folks which probably has a lot more users.

**Comment by rubyFeedback** [comment]
> We're missing QT as well for the KDE folks which probably has a lot more users.

That's a good point. We would also probably have to decide on which qt version
that is to be offered by libui-ng (if it were possible). I would assume at this point
in time it would be qt-6.

I remember that qt4 used to have ruby bindings, maintained by a few hobbyists
such as rdale. Then qt5 came out and it seemed too much work to write bindings
to it for ruby manually, so the old team kind of dispersed/vanished.

Would be cool if we could have something like swig or gobject-introspection for
all these C and C++ GUI libraries, and if that could then be used by libui-ng and
others to offer fast (but a simplified) access to all of them.

**Comment by rubyFeedback** [comment]
So these are a few add-on thoughts, not necessarily about Haiku + libui-ng, but
more in general. I have had a similar use case before, where I thought how
libui-ng would be pretty great for constrained systems, such as embedded 
devices. Here being able to display simple widgets, such as via libui-ng (and
in my case ruby) would be neat. I could then skip writing Java code probably.

The use case here is a bit similar: constrained devices, and HaikuOS (and its
widget set).

So, traditionally libui would have support for at the least Linux (via gtk),
Mac OSX and windows. As the thread here pointed out, also Haiku.

It would be nice if we could define a "standards ground" set of things needed
to support more toolkits - perhaps qt too, and the Haiku widget set. Perhaps
more than that. Kind of like a libui-specification. People could then refer
to it when implementing more support for other toolkits and platform.

For this, we may also have to give more flexibility to such a specification,
meaning that people do not need to conform to 100% of it, but just to a 
sufficient amount of it. Certain key widgets and key functionality.

I don't know how that could look, but for instance:

- buttons
- main window
- container widgets (such as hbox and vbox and grid widgets)

And perhaps a bit of styling behaviour (font size, colours and so forth).

Then, once that key (base) spec is done, people can add more advanced things
or so, such as tooltips. A tooltip is not ultimately necessary, but it would
be nice to support it. It would not necessarily be part of the libui-core
spec, but the primary extension of it, something like that.

Also, such a spec should be verifiable, so that people know what needs to
be done in order to support it.

Anyway. These are just a few rough ideas about this. The main point would
be that different people could write a bit of code, without needing to 
dedicate weeks of writing code, and you could have some support for this
or that toolkit or add-on. That could be maintained within libui-ng too,
rather than be spread out (projects often tend to die, so I think it would
be better to maintain it all under the same umbrella project).

These are just semi-random thoughts; I assume in practice it is much harder
to do, in particular as I assume most Haiku-devs are very busy, and for other
devs with more time they may not know the Haiku ecosystem (I don't know it,
for instance; I don't even know if there is API documentation on Haiku for
that).

**Comment by coolcoder613eb** [comment]
> I don't even know if there is API documentation on Haiku for
that

https://www.haiku-os.org/docs/api/
https://www.haiku-os.org/legacy-docs/bebook/
