### ISSUE TITLE
glcanvas?

### ISSUE THREAD

**Issue by blk750** [libui-ng/libui-ng#79]
Perhaps a gl canvas?

**Comment by msink** [comment]
If you mean `uiArea` with OpenGL backend - `uiGLArea` - it's possible on Linux/GTK and Windows, but what about macOS?

**Comment by blk750** [comment]
oh, there already is

**Comment by blk750** [comment]
i mean, there seems to be means for cocoa to make a gl context from a search.

**Comment by blk750** [comment]
it's discouraged, but it's still supported
https://www.quora.com/How-do-I-set-up-OpenGL-on-a-Mac

**Comment by cody271** [comment]
> Perhaps a gl canvas?

Hi @blk750, definitely. Please see old PR by @mischnic for [`uiOpenGLArea`](https://github.com/andlabs/libui/pull/405)

**Comment by cblc** [comment]
Do you have any ideas on how to bring that old PR back to life, @cody271 ?
Assuming it's "low on conflicts" (which perhaps is an optimistic assumption), do you think that the only thing pending would be to add unit tests, or do you know if there's still any important issue/limitation/missing feature?

**Comment by cody271** [comment]
> Do you have any ideas on how to bring that old PR back to life, @cody271 ?

Unfortunately, adding a proper 3D area control is a _lot_ of work still yet to be done..

First of all, starting with the existing PR, my [original comment](https://github.com/andlabs/libui/pull/405#issuecomment-417989157) there (from 2018) is still valid:
the Unix backend would have to be entirely rewritten to use the builtin Gtk control, instead of the X11 only re-implementation there. Otherwise you break Wayland desktops. (And probably breaks the new Gtk hardware accelerated control rendering pipeline as well..)

But that's really the least of our problems, sadly in those five years the state of cross platform 3D graphics has gotten quite complicated: exposing the native OpenGL support of each platform is simply no longer viable. Darwin no longer supports it, native OpenGL on Ventura is quite broken! DirectX on Windows has significantly better performance and consistency than OpenGL. Native OpenGL is effectively Unix only at this point in time. Even on Unix, Vulkan drivers are quickly becoming the better option.

The correct solution is to integrate with a 3D graphics API wrapper, instead of OpenGL directly:
[ANGLE](https://en.wikipedia.org/wiki/ANGLE_(software)) for simple 3D graphics, and maybe [WebGPU](https://en.wikipedia.org/wiki/WebGPU) for the more complex use cases.

**Comment by cblc** [comment]
I think OpenGL still has a future on the Mac, because of the number of apps which still use it, and I think that they fixed the broken status you mention in the last Ventura update. Anyway, I fully agree that it's too risky to 100% depend on OpenGL these days, because OS vendors are doing constant changes to everything and you never know what's going to be the recommended API tomorrow.

Said this, and precisely because of the volatility of graphics APIs these days, I've been thinking twice and now I believe that the best in graphics is to not reinvent the wheel: For example, SDL2 is written in C, and has great support for all the major graphics APIs and OS windowing systems. Also, because they have a lot of contributors, and because it's used for lots of games (and non-games too), when a vendor breaks an API, the SDL2 developers are of the first ones to notice, and to provide a working solution. I remember I took a look at how they started the Android port, and they even had device-specific bugfixes (I mean brand and model-specific). For achieving such a degree of support and response to problems, you need a lot of developers contributing.

So, now I tend to believe that the best option would be to enable **libui-ng** to run in a special mode where the app instance and the main window, and the app initialization are done by SDL2, and then **libui-ng** would create the GUI in dialog windows only (and in the app menu bar), but never adding widgets nor panels to the main window.

Some minimalist libs for native dialogs ([like this](https://github.com/mlabbe/nativefiledialog)) allow to do this with SDL2 apps.

As a plus, you get very desirable stuff for free: multiplatform audio playback, HiDPI support for the app (perhaps helping close [this](https://github.com/libui-ng/libui-ng/pull/147)), multitouch gestures (zoom/pan/rotate/etc) for the graphics canvas, and quite possible more things I'm forgetting now. Not to mention that SDL2 supports iOS and Android, which could help add support to mobile devices in the future, if so desired. Trying to rival all these things from **libui-ng** wouldn't be realistic, because the size of the developer team would need to be as big as SDL's.

Anyway, for making **libui-ng** capable of integrating with SDL2, these requirements should be met:

- In order to avoid making **libui-ng** depend on SDL2, the support for this mode should be configurable at compile time: if you don't need a graphics canvas, you don't need to have SDL2 installed.
- An special initialization mode in which it doesn't initialize app stuff and main window stuff which has been already initialized by SDL. **Open question: Would it be required to modify SDL so that it can give you a pointer to the app instance, or to the main window instance?** (I hope not, the native dialogs libs I said doesn't seem to need that).
- A setting (if necessary) for libui-ng dialog windows so that they are guaranteed to stay always on top of the main window created by SDL (I don't know if this is necessary or not).
- SDL apps work by polling the event queue (by the way, there's now a new SDL2 function call that makes the polling in a sleeping way, thus removing the CPU stress that this polling can cause in games). So, the app event loop should perhaps send back to the OS the app events that don't belong to the graphics canvas, so that the UI is not blocked (I say "perhaps", because again, I'm not sure if this point is necessary either).

I truly think that, for graphics canvas in **libui-ng**, this would be the most desired approach.

**Comment by AndyObtiva** [comment]
Would GLCanvas have support for 2D hardware acceleration in addition to 3D hardware acceleration?

I received an issue request on my [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui) Ruby GUI library about rendering ~2999 area shapes being slow:

https://github.com/AndyObtiva/glimmer-dsl-libui/issues/55

It is a node graph app with about a thousand nodes and a thousand edges.

<img width="912" alt="Screenshot 2023-08-18 at 4 55 06 PM" src="https://github.com/libui-ng/libui-ng/assets/23052/eb7003ee-eac1-4d79-ba6c-6622bf6ca2ee">

On my Mac Intel 2.6GHz 6-core Core i7, I noticed that it takes about 3 seconds to re-render all the nodes on every change (like when pressing the Refresh Nodes button). The only thing that is changing is the node/edge colors in my personally written sample to reproduce the problem. But, I assume the reporter of the issue might be interested in general updates to node/edge locations too too.

How do we speed up the rendering of thousands of shapes in an area (beyond 3 seconds)? Is GLCanvas the answer or should I re-report this in a different issue?

**Comment by cody271** [comment]
> Would GLCanvas have support for 2D hardware acceleration in addition to 3D hardware acceleration?
> 

`uiDrawContext` calls already use hardware accelerated 2D rendering by default on most platforms.

> 
> How do we speed up the rendering of thousands of shapes in an area (beyond 3 seconds)? Is GLCanvas the answer or should I re-report this in a different issue?

The overhead of a Ruby FFI bindings call is *orders of magnitude* slower than native code. This overhead isn't noticeable most of the time, as the number of FFI calls per second for typical `uiControl` usage patterns is quite low.

But where this approach will simply be way too slow is for complex graphics rendering loops.
(Hundreds or even thousands of FFI calls per second!)

**Comment by AndyObtiva** [comment]
> `uiDrawContext` calls already use hardware accelerated 2D rendering by default on most platforms.

Thank you for the clarification. Is `uiDrawContext` the same thing as `uiArea` in general or different? `uiArea` is what we're using.

@kojix2 I just saw `uiDrawContext` in `ui.h`, but I didn't see it in the last released version I have of the Ruby LibUI binding, and it might be different from `uiArea`. Is this a new feature that didn't make it into the Ruby LibUI binding yet?

**Comment by cody271** [comment]
Yes, same thing.

`uiArea` is the control type, `uiDrawContext` is the rendering engine wrapper to [CoreGraphics](https://en.wikipedia.org/wiki/Quartz_2D) / [Cairo](https://en.wikipedia.org/wiki/Cairo_(graphics)) / [Direct2D](https://en.wikipedia.org/wiki/Direct2d).

**Comment by cody271** [comment]
> @kou measured the time required to call a C function from Ruby with FFI and native C extension and concluded that FFI consumes about 10 to 100 times longer.
> 
I would suggest a native C extension just for the `uiDraw` calls, the rest of the bindings for controls can stay FFI.
